# Generated by Django 3.2.14 on 2022-07-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('val_annee', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'annee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assettype',
            fields=[
                ('id_asset', models.AutoField(primary_key=True, serialize=False)),
                ('name_asset', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'assettype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id_fund', models.AutoField(primary_key=True, serialize=False)),
                ('name_fund', models.CharField(max_length=50)),
                ('legal_structure', models.CharField(blank=True, max_length=50, null=True)),
                ('pays_domiciliation_fund', models.CharField(blank=True, max_length=20, null=True)),
                ('gp_alignement', models.FloatField(blank=True, db_column='GP_alignement', null=True)),
                ('open_close', models.CharField(blank=True, max_length=20, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('ltv_max', models.FloatField(blank=True, null=True)),
                ('ltv_current', models.FloatField(blank=True, null=True)),
                ('ltv_target', models.FloatField(blank=True, null=True)),
                ('gav_current', models.FloatField(blank=True, null=True)),
                ('gav_target', models.FloatField(blank=True, null=True)),
                ('nav_current', models.FloatField(blank=True, null=True)),
                ('dividende_net', models.FloatField(blank=True, null=True)),
                ('capital_growth', models.FloatField(blank=True, null=True)),
                ('total_net_return', models.FloatField(blank=True, null=True)),
                ('tri', models.FloatField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('nom_per_modif', models.CharField(blank=True, max_length=20, null=True)),
                ('min_ticket', models.FloatField(blank=True, null=True)),
                ('inception', models.DateField(blank=True, null=True)),
                ('nav_calculation_method', models.TextField(blank=True, null=True)),
                ('strategy_summary', models.TextField(blank=True, null=True)),
                ('queue_value', models.FloatField(blank=True, null=True)),
                ('queue_term', models.TextField(blank=True, null=True)),
                ('loan_interest', models.FloatField(blank=True, null=True)),
                ('loan_maturity', models.TextField(blank=True, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=30, null=True)),
                ('interest_rate_type', models.CharField(blank=True, max_length=30, null=True)),
                ('loan_capped', models.FloatField(blank=True, null=True)),
                ('asset_number', models.IntegerField(blank=True, null=True)),
                ('tenants', models.IntegerField(blank=True, null=True)),
                ('taux_occup_financiere', models.FloatField(blank=True, null=True)),
                ('taux_occup_physique', models.FloatField(blank=True, null=True)),
                ('management_fees', models.TextField(blank=True, null=True)),
                ('performance_fees', models.TextField(blank=True, null=True)),
                ('asset_acquisition_fees', models.TextField(blank=True, null=True)),
                ('asset_exit_fees', models.TextField(blank=True, null=True)),
                ('other_fees', models.TextField(blank=True, null=True)),
                ('ter_nav', models.FloatField(blank=True, null=True)),
                ('ter_gav', models.FloatField(blank=True, null=True)),
                ('tger_nav', models.FloatField(blank=True, null=True)),
                ('tger_gav', models.FloatField(blank=True, null=True)),
                ('portfolio_value', models.FloatField(blank=True, null=True)),
                ('walt', models.FloatField(blank=True, null=True)),
                ('walb', models.FloatField(blank=True, null=True)),
                ('sfdr', models.IntegerField(blank=True, null=True)),
                ('gresb', models.CharField(blank=True, max_length=4, null=True)),
                ('net_acquisition_income', models.FloatField(blank=True, null=True)),
                ('cash_and_cash', models.FloatField(blank=True, null=True)),
                ('erv', models.FloatField(blank=True, null=True)),
                ('redemption', models.TextField(blank=True, null=True)),
                ('forward_exchange_hedging', models.TextField(blank=True, null=True)),
                ('nbre_invetisseurs', models.IntegerField(blank=True, null=True)),
                ('ticket_moyen', models.FloatField(blank=True, null=True)),
                ('ticket_gros', models.FloatField(blank=True, null=True)),
                ('ticket_petit', models.FloatField(blank=True, null=True)),
                ('nbre_immeuble_labelise', models.IntegerField(blank=True, null=True)),
                ('fund_term', models.CharField(blank=True, max_length=10, null=True)),
                ('quaterly_reporting', models.TextField(blank=True, null=True)),
                ('desc_fund', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fund',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id_geo', models.AutoField(primary_key=True, serialize=False)),
                ('name_geo', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gp',
            fields=[
                ('id_gp', models.AutoField(primary_key=True, serialize=False)),
                ('name_gp', models.CharField(max_length=20)),
                ('name_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('prenoms_manager', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_manager', models.CharField(blank=True, max_length=25, null=True)),
                ('telephone_manager', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_perso', models.AutoField(primary_key=True, serialize=False)),
                ('name_per', models.CharField(blank=True, max_length=20, null=True)),
                ('prenoms_perso', models.CharField(blank=True, max_length=20, null=True)),
                ('email_perso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id_trim', models.AutoField(primary_key=True, serialize=False)),
                ('name_trim', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'trimestre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundAssettype',
            fields=[
                ('value_asset_type', models.FloatField(blank=True, null=True)),
                ('id_fund', models.OneToOneField(db_column='id_fund', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fund.fund')),
            ],
            options={
                'db_table': 'fund_assettype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundGeo',
            fields=[
                ('value_asset_geo', models.FloatField(blank=True, null=True)),
                ('id_fund', models.OneToOneField(db_column='id_fund', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fund.fund')),
            ],
            options={
                'db_table': 'fund_geo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FundPersonnel',
            fields=[
                ('id_fund', models.OneToOneField(db_column='id_fund', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='fund.fund')),
            ],
            options={
                'db_table': 'fund_personnel',
                'managed': False,
            },
        ),
    ]
