# Generated by Django 3.2.14 on 2022-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_perso', models.AutoField(primary_key=True, serialize=False)),
                ('name_per', models.CharField(blank=True, max_length=20, null=True)),
                ('prenoms_perso', models.CharField(blank=True, max_length=20, null=True)),
                ('email_perso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'personnel',
                'managed': False,
            },
        ),
    ]
